name: 'JSON Secrets Parser'
description: 'Reads a JSON-stringified secrets and extracts keys, then sets them to outputs.'
secrets:
  keys:
    description: 'A stringified JSON object containing secrets (or anything)'
    required: true
  keys:
    description: 'An comma separated of keys to parse out of the json object (e.g. staging.user, staging.pw)'
    required: true
outputs:
  key:
    description: 'The key + value of each key input (e.g. staging.user returns and output {user:"Joe Username"})'
    value: ${{ steps.set-outputs.outputs.user }}
runs:
  using: 'node20'
  main: 'index.js'