name: Test Secrets Parser

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test (staging or production)'
        required: true
        type: choice
        options:
          - staging
          - production

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run secrets-parser
        id: parse-secrets
        # uses: rynodivino/json-secrets-parser
        uses: ./.
        with:
          secrets: ${{ secrets.secrets }}
          keys: ${{ github.event.inputs.environment }}.username,${{ github.event.inputs.environment }}.password

      - name: Print outputs
        run: |
          echo "Username: ${{ steps.parse-secrets.outputs.username }}"
          echo "Password: ${{ steps.parse-secrets.outputs.password }}"